proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./certs:/etc/nginx/certs
    - ./vhost.d:/etc/nginx/vhost.d
    - ./challenges:/usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro

letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt
  volumes_from:
    - proxy
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certs:/etc/nginx/certs:rw
